### ISSUE TITLE
PartiQL-Environment Tracking Issue

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1496]
## What?

_This issue is to help the review of the SPI dependency switch; the review will be broken down into several PRs targeting [v1-metadata](https://github.com/partiql/partiql-lang-kotlin/tree/v1-metadata)_

## Reviews
- [ ] Define Interfaces
    - Reviewer Alan
- [ ] Define prelude (in parallel to 1)
    * Reviewers Josh and Arash
    * https://github.com/partiql/partiql-lang-kotlin/pull/1490
- [ ] Update plugins (partiql-local and partiql-memory)
- [ ] Update partiql-planner
- [ ] Fix build / update tests

Branches

- [v1-metadata](https://github.com/partiql/partiql-lang-kotlin/tree/v1-metadata) — destination branch
- [v1-prelude](https://github.com/partiql/partiql-lang-kotlin/tree/v1-prelude) — dump of functions to .ion files
- v1-fns — current working/hacking branch
