### ISSUE TITLE
[V1] Plan cleanup tracking issue

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1612]
## Description

This issue tracks the required work for cleaning up the plans and getting tests to pass.

* [x] Get a successful build
* [x] Add types to plan impl constructors.
* [x] PR to merge previous changes into V1  (#1617)

## Disabled Tests (to-be-fixed)

Tests are fixed by, #1611

**Comment by RCHowell** [comment]
#1611 fixes the `:partiql-eval` build
