### ISSUE TITLE
[V1] Tracking issue for sink and source APIs for PartiQL data streams.

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1654]
## Description

This issue is a tracking issue for several PRs in a sequence to finalize value representations along with the reader/writer implementations.

## Tasks

* [ ] Move datetime to values spi
* [ ] Package datum into SPI datum
* [ ] Push sink/source APIs for PartiQL streams
* [ ] Add default sink/source implementations.
* [ ] Split ion/json/csv implementations from SPI package.
* [ ] Define type provider interface for different variant forms.
