### ISSUE TITLE
[V1] Complete datetime and interval types

### ISSUE THREAD

**Issue by rchowell** [partiql/partiql-lang-kotlin#1657]
## Description

PartiQL does not implement the SQL datetime operators; here's what needs to be done: see SQL-99 4.7.3 p.29.

Working PR – #1656

**Tasks**

- [x] Define datetime on datum
- [x] Define interval on ptype
- [x] Define interval on datum
- [x] Add INTERVAL_YM and INTERVAL_DT to PTYPE
- [ ] `datetime - datetime   -> interval`
- [ ] `datetime + interval   -> datetime`
- [ ] `datetime - interval   -> datetime`
- [ ] `interval + datetime   -> datetime`
- [ ] `interval + interval   -> interval`
- [ ] `interval - interval   -> interval`
- [ ] `interval * numeric    -> interval`
- [ ] `interval / numeric    -> interval`
- [ ] `numeric  * interval   -> interval`

**Comment by RCHowell** [comment]
Awaiting PR feedback on additions to Datum before fixing the build hence still draft. Fixing the builtin functions will be a lot of work which is subject to change based upon the modeling.

**Comment by RCHowell** [comment]
need rebase on #1658

**Comment by RCHowell** [comment]
After that, I'll address the build. Working on plans now.

**Comment by alancai98** [comment]
Adding INTERVAL was attempted in https://github.com/partiql/partiql-lang-kotlin/pull/1656. A potential lesson learned is that Java's duration and period may not properly model SQL's INTERVAL semantics. Still need some further investigation here. We may need to introduce a separate class to model properly.
