### ISSUE TITLE
[V1] SPI Feedback Cleanup

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1660]
## Description

This is a tracking issue for finalization/cleanup efforts for the SPI classes.

## Tasks

- [ ] Split getTable(identifier) functionality to leverage getTable(name)
- [ ] Remove some default impls so its clear what to implement
- [ ] Make function instances easier to use
- [ ] Have hidden PartiQL catalog (env calls it directly)
