### ISSUE TITLE
[V1] Plan cleanup and finalization

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1661]
## Description

This is a tracking issue for plan cleanup efforts and finalization, see #1665 

## Tasks

- [x] Convert interfaces to Java
- [x] Make full tree since we have the Operator interface now.
- [x] Remove default methods
- [x] Update RelScan input name
- [x] Rewriter
- [x] Factory updates
- [x] Builder updates (punted to #1664)
- [x] Fix the build! integration hell 😄

**Comment by RCHowell** [comment]
need rebase on #1658
