### ISSUE TITLE
[V1] Post rc.3 plan cleanup follow-up issue

### ISSUE THREAD

**Issue by rchowell** [partiql/partiql-lang-kotlin#1664]
## Description

This issue holds a list of follow-up actions for post rc.3 plan development.

## Tasks

- [ ] Collation getColumn should return a column index rather than an expression.
- [ ] RelAggregate group strategy
- [ ] Document all arg ordering (import because of efficient serde and rewriter rules/strategies!)
- [ ] #1575 
- [ ] Planner subquery support (proper)
- [ ] Consider non-lateral cross join and equijoins (both not in spec)
- [ ] Add back stack-style builders
- [ ] Consider "replace" methods for mutability and "copy" for immutable patterns
- [ ] Document children with vararg children support (coalesce, array, bag, etc)
- [ ] Fix cross join in planner to use correlate
- [ ] Make error return UNKNOWN rather than dynamic.
