### ISSUE TITLE
Add support for set operators `UNION`, `INTERSECT` `EXCEPT`

### ISSUE THREAD

**Issue by therapon** [partiql/partiql-lang-kotlin#184]
## Overview

Add support for set operators `UNION`, `INTERSECT` `EXCEPT`

## Tasks
- [x] https://github.com/partiql/partiql-docs/pull/7
- [x] Define OUTER variants in the lexer/parser/ast
- [x] Implement the simpler OUTER variants
- [ ] Implement SQL conformant UNION, INTERSECT, EXCEPT -- depends on partiql-spec [#45](https://github.com/partiql/partiql-lang/issues/22).

A follow-up to this ticket can be #1015, for the  `CORRESPONDING BY` clause in these operators.

**Comment by RCHowell** [comment]
The RFC for set operator behavior has been merged. Implementation is next.
 
https://github.com/partiql/partiql-docs/blob/main/drafts/0007-RFC-BAG-OPERATORS.md

**Comment by RCHowell** [comment]
Added a sub task list to issue description

**Comment by alancai98** [comment]
> The RFC for set operator behavior has been merged. Implementation is next.
> 
> https://github.com/partiql/partiql-docs/blob/main/drafts/0007-RFC-BAG-OPERATORS.md

FYI the above RFC was moved from `drafts/` to the `RFC`s folder: https://github.com/partiql/partiql-docs/blob/main/RFCs/0007-rfc-bag-operators.md
