### ISSUE TITLE
Replace legacy evaluator with planner based implementation

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#758]
## Motivation
We will be replacing the legacy evaluator with a similar evaluator which has two distinct improvements.
1. It enables support for DML/DDL
2. It expands SFW AST nodes into the equivalent relational algebra operators.

Expansion to relational algebra operators is useful for customers to provide their own plan optimizations as well as include their own operator implementations. 

## Goal

To have feature parity with the existing evaluator compiler, as well as expose the added functionality required by the customers who need a planner.

## Subtasks
- [x] Split compilation pipeline responsibilities #722 
- [x] Remove the experimental planner
- [ ] Reduce external PIG domain to only PartiQLPhysical (*** hold)
- [x] Pass all evaluator tests with the new planner 
- [x] #781 
- [x] #794 
- [x] #800 
- [x] #814 
- [x] #853

**Comment by RCHowell** [comment]
See V1 evaluator, currently at 94%+ conformance compared to EvaluatingCompiler's 89%

 https://github.com/partiql/partiql-lang-kotlin/tree/v1/partiql-eval
